### PR TITLE
Add default fractions

### PR DESCRIPTION
**Pull request by mohameditani**
Reference: https://www.localeplanet.com/icu/currency.html

### CODE REVIEW

**Comment by funky-monkey** [comment]
Thanks for this addition! Could you also add to/update the readme?

**Comment by funky-monkey** [comment]
@mohameditani if you can add a section in the readme about what this does and how to use it, i'll merge this into the base branch

**Comment by mohameditani** [comment]
Hello, sorry for the late reply.

Description added.

Mohamed Alitani

Phone +9613797236

**Review by funky-monkey — APPROVED** [review]

**Comment by funky-monkey** [comment]
Hi @mohameditani,

Can you send me a practical example of how to use this? Then I can include it in the readme.

Best, 
Sidney

**Comment by mohameditani** [comment]
Sure, here it is:

*func* tansform(price: Double, country: IsoCountryInfo) -> Double {



        *let* fractionDigits = country.fractionDigits



        *let* amount = price * pow(10.0, Double(fractionDigits))



        *return* amount

    }


Mohamed Alitani

Phone +9613797236

**Comment by mohameditani** [comment]
To elaborate more on this previous example:

I was working on an integration with a payment system for a restaurant app.
The payment system only accepts receiving the total amount as fractions
based on the selected currency. By using the function, it allows me to
convert any amount with a currency to fractions value.

Hope it helps!


Mohamed Alitani

Phone +9613797236

**Comment by funky-monkey** [comment]
Thanks for the explanation.
Would something like this be correct? Shall i include this in the docs? What would `let digits` return? (I cant test this code right now)

```
func transformToDigits(price: Double, country: IsoCountryInfo) -> Double {
  let fractionDigits = country.fractionDigits
  let amount = price * pow(10.0, Double(fractionDigits))
  return amount
}

let priceOfCoffee = 2.05
let country = IsoCountryCodes.searchByName("Italy")
let digits = transformToDigits(priceOfCoffee, country)
```

**Comment by funky-monkey** [comment]
I'm thinking now, couldn't you get your created `fractionDigits` from Apple's `NumberFormatter` somewhere? Or is that not what you are after? I think it has a currency style

**Comment by mohameditani** [comment]
Since the currency of Italy is the euro so the fraction digits will be 2.

Result: digits = 10^2 * 2.05 = 205 cents

Mohamed Alitani

Phone +9613797236

**Comment by mohameditani** [comment]
NumberFormatter only provides currency code, symbol,
decimal/grouping separator, and not fraction digits.

Mohamed Alitani

Phone +9613797236

**Comment by funky-monkey** [comment]
Great stuff, i'll update the docs an bump the version for SPM.

**Comment by mohameditani** [comment]
Much appreciated! Cheers

**Comment by funky-monkey** [comment]
Most welcome! 
Its tagged and updated. Enjoy!

**Pull request merged**
